---
# tasks file for roles/helm
- name: Add Helm's Official GPG key
  shell: curl https://baltocdn.com/helm/signing.asc | gpg --yes --dearmor -o /usr/share/keyrings/helm.gpg

- name: Add Helm repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main"
    filename: helm-stable-debian
    state: present

- name: Update APT package index
  apt:
    update_cache: yes

- name: Install Helm
  apt:
    name: helm
    state: latest