---
# tasks file for roles/prerequisites
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
- name: Install prerequisites
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg
    state: present
