---
- name: Join Worker Nodes to the Cluster
  hosts: workers
  become: true
  vars_files:
    - /etc/ansible/vars/kubeadm_join.yml
  tasks:
    - name: Execute join command
      ansible.builtin.command: "{{ kubeadm_join_command }}"
      changed_when: false
